@echo off
title Sam-NorthDev System Scanner
color 0A

echo ========================================
echo    SYSTEM AUDIT TOOL - VERSION 1.1
echo ========================================
echo.
echo Please wait... Gathering system information...

:: Gather all info into the report file
echo [FULL SYSTEM REPORT] > "%userprofile%\Desktop\Full_System_Audit.txt"
echo Generated by Sam-NorthDev >> "%userprofile%\Desktop\Full_System_Audit.txt"
echo ---------------------------------------- >> "%userprofile%\Desktop\Full_System_Audit.txt"

:: Using systeminfo (The one that actually worked for you)
systeminfo >> "%userprofile%\Desktop\Full_System_Audit.txt"

:: Adding Network info separately for more detail
echo. >> "%userprofile%\Desktop\Full_System_Audit.txt"
echo [NETWORK DETAILS] >> "%userprofile%\Desktop\Full_System_Audit.txt"
ipconfig /all >> "%userprofile%\Desktop\Full_System_Audit.txt"

echo.
echo ========================================
echo [SUCCESS] Report saved to your Desktop!
echo File Name: Full_System_Audit.txt
echo ========================================
pause
